[tool.poetry]
name = "augmented_gpt"
version = "0.3.0"
description = "ChatGPT API wrapper, argumented with functions"
# documentation = "https://github.com/wenyuzhao/augmented-gpt"
authors = ["Wenyu Zhao <wenyu.zhao@anu.edu.au>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/wenyuzhao/augmented-gpt"
packages = [{ include = "augmented_gpt" }]
keywords = ["chatgpt", "gpt"]

[tool.poetry.dependencies]
python = ">=3.10"
python-dotenv = "^1.0.0"
pandas = ">= 2.0.0"
numpy = ">=1.22"
openai = { version = "1.2.3" }
scikit-learn = "^1.4.1.post1"


[tool.poetry.group.dev.dependencies]
ipykernel = "^6.23.2"
pytest = "^7.3.2"
pytest-asyncio = "^0.21.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
